### ISSUE TITLE
preventing overflow with short and ushort

### ISSUE THREAD

**Issue by SadToBeNep** [draconware-dev/SpanExtensions.Net#14]
# Not really a feature, rather a preventive suggestion

With the `.Sum()` function the return type of the function should be **int** for **short** and **ushort**, because if we try to sum up a long list  of shorts, it can easily overflow and cause an OverflowException

**If there is a need for it, I can try to implement it myself**

**Comment by dragon7307** [comment]
I'll look into it.
This seems a good call at first glance.
The problem is, that **.Net** does not even define the `Sum` Method for `short` and `ushort`, neither does it for `byte` and `sbyte`. 
Probably for precisely this reason.  
However I am not sure, if changing the return type is actually a good idea, since then the method would be essentially the same as the int method version, so maybe It'd be better to just remove the overload for these types and just use the int version for all these types.  
I'll see how this will turn out, but many thanks for bringing this to my attention.

**Comment by dragon7307** [comment]
I have decided that the change can unfortunately not be made!! 
 
**Reasoning:** 
Besides the fact that no sufficient solution has been found sofar, it is not possible to have a different return type, than the passed type, since for **.Net 7** and above the behaviour is implemented via the `INumber<T>`  interface to allow for extensibility. This however does not permit to return a type other than the used type itself. Neither is removing the methods for types smaller than `int` an option, because that would lead to the same issue, since if for example a short would be passed in **.Net 5** it would use the int overload, but if one would update to .**Net 7+** then it would use the `INumber<T>` overload and return a `short` instead. This could lead to an overflow that didn't exist in previous versions.     
 
**Conclusion:**   
For above reasons, the overloads for `short`, `ushort`, `byte` and `sbyte` must remain as not  to introduce any breaking changes between different versions of .Net.  
Still thanks for pointing this out. Feel free to propose possible ways to implement the feature I may have overlooked.

**Comment by dragon7307** [comment]
I have decided that the change can unfortunately not be made!!

Reasoning:
Besides the fact that no sufficient solution has been found sofar, it is not possible to have a different return type, than the passed type, since for .Net 7 and above the behaviour is implemented via the INumber<T> interface to allow for extensibility. This however does not permit to return a type other than the used type itself. Neither is removing the methods for types smaller than int an option, because that would lead to the same issue, since if for example a short would be passed in .Net 5 it would use the int overload, but if one would update to .Net 7+ then it would use the INumber<T> overload and return a short instead. This could lead to an overflow that didn't exist in previous versions.

Conclusion:
For above reasons, the overloads for short, ushort, byte and sbyte must remain as not to introduce any breaking changes between different versions of .Net.
Still thanks for pointing this out. Feel free to propose possible ways to implement the feature I may have overlooked.
