### ISSUE TITLE
Doesn't work with Path.PathSeparator as delimeter, but works with '\\'

### ISSUE THREAD

**Issue by VafArt** [draconware-dev/SpanExtensions.Net#4]
**Describe the bug**  
Doesnt work with Path.PathSeparator as delimeter, but works with '\\'

**To Reproduce**  
using SpanExtensions;
var path = @"C:\Users\ArthurPC\source\repos\a.vafin\PhotoService\products";
foreach(var e in ReadOnlySpanExtensions.Split(path, Path.PathSeparator)) // doesn't split, but works with '\\' in windows
{
    Console.WriteLine(e.ToString());
}

**Expected behavior**  
Console Input:
C:
Users
ArthurPC
source
repos
a.vafin
PhotoService
products

**Comment by dragon7307** [comment]
Hey, Thank you for reporting this bug.
However, this "bug", does not appear to be a bug of the library at all, but instead it seems to me that there is a misunderstanding concerning **.Net terminology** here. You are trying to delimit a path delimited by a "\\". 
`Path.PathSeparator` is defined as a semicolon on windows, as can be seen [here](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.pathseparator?view=net-8.0). As the name suggests, `Path.PathSeparator` is used to separate actual paths, like yours from another, for example in environment variables.
 So essentially you have been trying to delimit your path with a semicolon as a delimiter, and you got the correct output, since your path didn't include any semicolons.  What you probably actually wanted to do, is use `Path.DirectorySeparatorChar`, which returns the platform specific delimiter for directories and files, not entire paths. 
This should fix your problem. If not, feel free to open another issue.
