### ISSUE TITLE
Ambiguous call between ReadOnlySpanExtensions and SpanExtensions

### ISSUE THREAD

**Issue by Guiorgy** [draconware-dev/SpanExtensions.Net#6]
**Describe the bug**  
The extension methods in `SpanExtensions` and `ReadOnlySpanExtensions` have the exact same signature, which causes a `CS0121` error, for example: `Error	CS0121	The call is ambiguous between the following methods or properties: 'ReadOnlySpanExtensions.Split<T>(ReadOnlySpan<T>, T)' and 'SpanExtensions.Split<T>(ReadOnlySpan<T>, T)'`

I am assuming the methods inside `SpanExtensions` were meant to accept `Span<T>` instead of `ReadOnlySpan<T>`?

**Version**  
1.2.0

**Additional context**   
I'd recommend having unit tests to catch such problems.

**Comment by dragon7307** [comment]
Hey,
Thanks for bringing this to my attention, I appreciate the support.  
I will definitely implement various testing mechanisms, as time goes on, however I have not yet found the time to do so.  
This bug is fixed in the latest patch Version 1.2.1 and the previous version that are affected will be deprecated!!
